name: test_env_intake-axds
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - intake>=0.6.7
  - intake-xarray
  - model_catalogs
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
    # - intake>=0.6.7
    # - intake-xarray
